### PR TITLE
Reenable Windows tests

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@samuelcolvin Have you got any time to check out this error? Seems grablib fails with a `UnicodeEncodeError` on Windows (although the exception itself seems to come from click).

**Comment by Dreamsorcerer** [comment]
@samuelcolvin Also, do you have admin access? I'd like pyup removed and the required status set on the 3.9 tests (otherwise Dependabot will auto-merge broken dependencies).

**Comment by samuelcolvin** [comment]
Thanks, I'll try to look next week.

**Comment by samuelcolvin** [comment]
@Dreamsorcerer I've made you an admin. I'll look at grablib now.

**Comment by samuelcolvin** [comment]
@Dreamsorcerer please please can you use informative names for branches in github.

image

Couldn't be less helpful

**Comment by samuelcolvin** [comment]
as explained [here](https://github.com/samuelcolvin/python-devtools/pull/93#issuecomment-913188711) windows tests were passing when they shouldn't be.

**Comment by Dreamsorcerer** [comment]
Seems the problem is only deprecation warnings internal to python (which is a result of a change I got merged into the last 3.9 release). Looks like everything is running now after your previous change.

Though curious the warnings didn't fail the tests for ubuntu/mac.

**Comment by Dreamsorcerer** [comment]
Also, I don't see any setting for pyup. Is it managed at https://pyup.io/? Would be nice to disable it, as dependabot should be working and auto-merging.

**Comment by samuelcolvin** [comment]
I deleted the webhooks.

**Comment by Dreamsorcerer** [comment]
> I deleted the webhooks.

Still seem to be coming in for some reason:
https://github.com/aio-libs/aiohttp-devtools/pull/337

**Pull request merged**
