### PR TITLE
set_loop for app check, allow app_factory()

### LINKED ISSUE #88: app.loop is not defined during pre-check
Hello,

I noticed a difference between running my application directly and using aiohttp-devtools.

The web.run_app of aiohttp fires `on_startup` after the call to `make_handler` which defines the loop on the app instance. In aiohttp-devtools, the pre-check fires `on_startup` and `on_cleanup` directly on the Application instance it finds in a module without setting the loop.

So if on a `on_startup` handler you create a task (using the loop) it will not work because loop is None at that point. The official example of aiohttp on background task is a good example:

http://pythonhosted.org/aiohttp/web.html#background-tasks

```python
async def listen_to_redis(app):
    try:
        sub = await aioredis.create_redis(('localhost', 6379), loop=app.loop)
        ch, *_ = await sub.subscribe('news')
        async for msg in ch.iter(encoding='utf-8'):
            # Forward message to all connected websockets:
            for ws in app['websockets']:
                ws.send_str('{}: {}'.format(ch.name, msg))
    except asyncio.CancelledError:
        pass
    finally:
        await sub.unsubscribe(ch.name)
        await sub.quit()


async def start_background_tasks(app):
    app['redis_listener'] = app.loop.create_task(listen_to_redis(app)) # <--------- HERE


async def cleanup_background_tasks(app):
    app['redis_listener'].cancel()
    await app['redis_listener']


app = web.Application()
app.on_startup.append(start_background_tasks)
app.on_cleanup.append(cleanup_background_tasks)
web.run_app(app)
```

The only solution I have at this point is deactivating the pre-checks...

### PR DESCRIPTION
**Pull request by samuelcolvin**
fixes #88.

### CODE REVIEW

**Comment by asvetlov** [comment]
Would you accept coroutine as `app_factory`?

**Comment by samuelcolvin** [comment]
Easy enough to do.

I'm not sure how that would work when running the code in production. Eg. Gunicorn doesn't accept a coroutine, and if you using web.run_app(), you'd have to do something ugly with `loop.run_until_complete`.

Why would a coroutine be useful? surely anything requiring a running loop can be doing in start coroutines? 

Perhaps having `app_factory` as a coroutine could encourage people to setup their app in a way which will be hard to deploy?

Very happy to add the functionality if it's useful.

**Comment by asvetlov** [comment]
Well, let's discuss.
My main motivation is creating every async object (the object that should cooperate with asyncio loop) inside a coroutine.
It allows to skip explicit event loop passing but get implicit running loop used for coro execution.
Maybe we end up with something like `run_forever()` from https://github.com/python/asyncio/pull/465 
I still don't know how to better integrate this approach with gunicorn.
We could add support for coroutine factory to `aiohttp.worker` easy though.
And after that got smoothly to dropping `._init_loop()` trick at all.

**Comment by samuelcolvin** [comment]
Let's leave the coroutine question for now. Happy to add it later if it's needed.

**Pull request merged**
