### PR TITLE
Configure AppVeyor integration

### PR DESCRIPTION
**Pull request by webknjaz**
Related to #194: if someone uses Windows, let's at least put some of the tests it into corresponding CI.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Great, will look properly tomorrow.

**Comment by webknjaz** [comment]
Okay, I've adjusted a few tests to pass under Windows, but had to "skip" some which seemed to need a lot of time to figure out whether it's even possible to run those in AppVeyor. I don't have Windows either, so it was like abusing AppVeyor and trying to guess how to fix it :)

*/me hopes to have a GitHub App integration someday to keep all CIs in org in sync and up to standard...*

**Comment by webknjaz** [comment]
I guess this could be accepted as is, and it future someone could try to figure out "ignored" tests one by one for simplicity.

**Comment by webknjaz** [comment]
@samuelcolvin I've enabled AppVeyor to show individual test runs (and their execution time, stdout, strerr) from xml report.
Demo: https://ci.appveyor.com/project/aio-libs/aiohttp-devtools/build/1.0.56/job/pw7ebhebedi8kv3u/tests

**Comment by samuelcolvin** [comment]
awesome. Thank you very much.

**Pull request merged**
