### PR TITLE
infering host from request

### PR DESCRIPTION
**Pull request by samuelcolvin**
Extending #71.

### CODE REVIEW

**Comment by samuelcolvin** [comment]
Hi @iSevenDays, could you review this and check it works for your case.

Although the `--host` argument is still available, you shouldn't need it - the server should set the host for livereload and static based on the request header.

Let me know if you have any questions.

**Comment by samuelcolvin** [comment]
ping @iSevenDays, do you want to help with this?

**Comment by iSevenDays** [comment]
Hi @samuelcolvin 

Currently all this day I've been using commit 750611caf4ce660ec594896a358d0829a321d19b (add better tests for modify_main_app) and I had no issues with it.

PYTHONPATH='..' adev runserver . --host 192.168.76.7
[21:54:02] pre-check enabled, checking app factory
[21:54:02] Starting dev server at http://192.168.76.7:8000 ●
[21:54:02] Starting aux server at http://192.168.76.7:8001 ◆

When launching without host argument, I see that everything works as it was with host.

[21:56:51] pre-check enabled, checking app factory
[21:56:51] Starting dev server at http://localhost:8000 ●
[21:56:51] Starting aux server at http://localhost:8001 ◆

On other PC I see a script in body pointing to correct host

<script src="http:/192.168.76.2:8001/livereload.js"></script>

Thank you for the improvement!

**Comment by samuelcolvin** [comment]
great, thanks.

**Pull request merged**
