### PR TITLE
Fix missing JS files

### LINKED ISSUE #395: v1.0 broken (missing JS)
The deploy steps seem to miss running `grablib` which is needed to include the JS files.

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Fixes #395

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz I'm not so familiar with the packaging process. What's the best way to fix this issue? The deploy process needs to run `grablib` to download the JS files.

I see there is a step in the CI to run this for the tests, should I just add the same step before `python -m build`? Or is there some way to add it to setup.py or similar and run it as part of the build step?

**Comment by Dreamsorcerer** [comment]
I'm now suddenly getting random test failures as well, which weren't happening an hour ago..

**Comment by webknjaz** [comment]
> I see there is a step in the CI to run this for the tests, should I just add the same step before `python -m build`? Or is there some way to add it to setup.py or similar and run it as part of the build step?

I think it's probably best to add it on PEP 517 level which could be implemented using an in-tree build backend that wraps the setuptools' one. An example would be https://github.com/ansible/pylibssh/blob/206c222/bin/pep517_backend/_backend.py#L190-L192 + https://github.com/ansible/pylibssh/blob/206c222/pyproject.toml#L16-L17, except you'd need to wrap `build_sdist` and not `build_wheel`. Of course, it's also possible to just wrap the `sdist` command right in `setup.py` but I personally dislike this approach.

**Comment by Dreamsorcerer** [comment]
The deploy step also doesn't recognise `1.0.post0` as an acceptable version:
`ValueError: Cannot find TOWNCRIER version head mark ('(?P<version>[0-9][0-9.abcr]+)\\s+\\(\\d+-\\d+-\\d+\\)\n====+\n?')`

**Comment by webknjaz** [comment]
> I'm now suddenly getting random test failures as well, which weren't happening an hour ago..

That doesn't seem related. `pytest` is set up to error out on warnings but those warnings are flaky. I looked at one, it was a `ResourceWarning` that was happening because of some race conditions and file descriptors not being closed before `loop.close()`.

**Comment by Dreamsorcerer** [comment]
> That doesn't seem related. `pytest` is set up to error out on warnings but those warnings are flaky.

Yeah, I just saw it 3 times in this PR, yet hadn't seen it in the previous 20 or so PRs. And the only code I can find relating to it, uses `with open()`, which should not result in this warning.

**Comment by webknjaz** [comment]
Yep, those are hard to trace. I think they are caused by aiohttp internals. I've seen these failures there and adding `await asyncio.sleep()` in a few places helped IIRC.

**Comment by webknjaz** [comment]
> The deploy step also doesn't recognise `1.0.post0` as an acceptable version: `ValueError: Cannot find TOWNCRIER version head mark ('(?P<version>[0-9][0-9.abcr]+)\\s+\\(\\d+-\\d+-\\d+\\)\n====+\n?')`

That's probably a limitation of `aio-libs/get-releasenote` — you'd need to debug it to see how it should be fixed. Andrew wrote it, I haven't looked too deep into the implementation. I'd likely implement it differently but I don't have time — I'm working on ultimate reusable workflow automation for tox-based projects (demo: https://github.com/webknjaz/tox-gha-test/actions/runs/1636261551) and there are at least a few components that may eventually get reused here too.

**Comment by Dreamsorcerer** [comment]
I figure just this? https://github.com/aio-libs/get-releasenote/pull/14

**Comment by webknjaz** [comment]
Probably.

**Pull request merged**
